# .github/workflows/scheduled-builds.yml
name: Trigger Site Rebuild on a CRON Schedule

permissions: write-all

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs: {}
jobs:
  status:
    name: print-status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check permissions
        run: ls -shalt 
      - name: Execute
        env:
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: >-
          go run ./cmd status
          echo "::set-env name=REFRESH_TOKEN::$REFRESH_TOKEN"
      - name: Set token output
        id: refreshtoken
        run: >-
            echo "::set-output name=REFRESH_TOKEN::$(
              cat refresh.token
            )"
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'REFRESH_TOKEN'
          value: "${{ steps.refreshtoken.outputs.REFRESH_TOKEN }}"
          repository: hmanzur/actions-set-secret
          token: ${{ secrets.GITHUB_TOKEN }}
